# -*- Perl -*-
######################################################################
__END__

=pod

=head1 NAME

voneline - Put one Verilog structural instantion per line

=head1 SYNOPSIS

  voneline < <infile> > <outfile>

=head1 DESCRIPTION

Voneline is a filter which takes Verilog structural netlists in stdin.  It
changes the whitespace to have a single instantiation per line.  This
compresses the file, and makes it easy to grep for instantiations.

=head1 ARGUMENTS

=over 4

=item --no-comments

Strip comments.

=item --version

Print program version and exit.

=item --width I<number>

By default, voneline will create lines that fit an entire instantiation and
are too long for other tools.  With --width, the next comma after that
column will appear on the next line.  (So choose a width a few hundred
characters shorter then the tool's maximum.)

=back

=head1 DISTRIBUTION

The latest version is available from L<http://www.veripool.org/voneline>.

Copyright 1998-2019 by Wilson Snyder.  This package is free software; you
can redistribute it and/or modify it under the terms of either the GNU
Lesser General Public License or the Perl Artistic License.

=head1 AUTHORS

Wilson Snyder <wsnyder@wsnyder.org>

=cut
######################################################################
